local b = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/'
local function Base64Decode(data)
    data = string.gsub(data, '[^'..b..'=]', '')
    return (data:gsub('.', function(x)
        if (x == '=') then return '' end
        local r,f='',(b:find(x)-1)
        for i=6,1,-1 do r=r..(f%2^i-f%2^(i-1)>0 and '1' or '0') end
        return r;
    end):gsub('%d%d%d?%d?%d?%d?%d?%d?', function(x)
        if (#x ~= 8) then return '' end
        local c=0
        for i=1,8 do c=c+(x:sub(i,i)=='1' and 2^(8-i) or 0) end
        return string.char(c)
    end))
end

assert(load(Base64Decode("G0x1YVIBBAQECBkNChoNCgECC0AIS0BKQA0KQEtASkBBDQpAS0BKQQ0KQEtASkBCDQpAS0BKQg0KQEtASkBDDQpAS0BKQA0KQEtASkQNCkBLQEpEDQpAS0BKRQ0KQEtASkUNCkBLQEpFDQpAS0BKQg0KQEtASkYNCkBLQEpHDQpAS0BKRA0KQEtASkcNCkBLQEpASA0KQEtASkgNCkBLQEpCDQpAS0BKQg0KQEtASkUNCkBLQEpKDQpAS0BKSg0KQEtASkBCDQpAS0BKQEsNCkBLQEpLDQpAS0BKQEwNCkBLQEpMDQpAS0BKQE0NCkBLQEpCDQpAS0BKTg0KQEtASksNCkBLQEpLDQpAS0BKSw0KQEtASkINCkBLQEpPDQpAS0BKRA0KQEtASkQNCkBLQEpCDQpAS0BKRQ0KQEtASkBLDQpAS0BKQFENCkBLQEpEDQpAS0BKSg0KQEtASkcNCkBLQEpCDQpAS0BKQEwNCkBLQEpAQQ0KQEtASkcNCkBLQEpFDQpAS0BKQg0KQEtASlQNCkBLQEpUDQpAS0BKVQ0KQEtASkcNCkBLQEpATA0KQEtASkBLDQpAS0BKRQ0KQEtASlYNCkBLQEpFDQpAS0BKQg0KQEtASkcNCkBLQEpATA0KQEtASkcNCkBLQEpEDQpACB9hBA0KVXNlckNoZWNrBBAxMFRhZ2VEdXJjaGZhbGwEBERheQQEMDUyBBA0IDggbDUgSTYgMjMgNDIEBDAzMAQQQWx3YXlzSW5UaGVNb29kBAQxMjQEDQpiZXRsZW5lZGR5ZGQEBDA0NQQLYnJ1enluc2VubgQEMzY2BBBicmlnaHQgZGF5bGlnaHQEBDAyNgQQQmx1bWl4aWZpY2F0aW9uBAhCMEFUMjQxBAQwNDQEDEJhc3RpYW5WQjY5BAQwODEEDQpjYWp2cHRreHgEBDAzNwQJQ2FuZWxvUkQEC0NvbXBicm9hcmsEBDAyNAQPQ1lCRVJDMFJOMDIwNzcEDQpjZWl0aGFybGluZGEEBDEwMAQOQ2FsYW1pdHkgMjgxMAQEMDgwBAtjdXJmYXJydWlkBAlkYW5pYWw4MQQEMDcxBAdlbGx6ZXIEBDA1MAQNCkV6IEJvbWJhc3RpYwQEMDY2BA0KZmVsaXphYnJpYWx5BBBHb3R0IFplcnN0cmVyBAdnaHJqb3YEB2dydXl4eAQEMDYyBA0KZWFydGJyb2tlbgQEMDI5BAtIZWxsc2luZzI0BAdocm16c20EBDA1MQQNCmhhcHB5Z29nbwQEMDY0BBBJIGdvdCB0aGUgdmlydXMEBDA3OAQRSk0gTmV2ZXIgR2l2ZSBVcAQEMDI1BAtLYWJvb200MjAxBAQwMzYEC2tyYXBvbnRpbmsECWt1a2FjYWRhBAQwNTgEDktlcmlzYWlzZW1vYW4EDQpLbm90dHlSZWdyZXQEDktuaWZlSGV4bGVyNjQECUx1eG5uYQQNCkx1a3lub0xVTAQEMDczBA5Mb3JkIExlYWZhckJSBAdsYWZmeXMECU1hZGE0OTEwBAtNSU5TVFkEC01hcnRpbmFsVmcECW1ma2J2Zml2BAQwNDYEC00gRm9yIE1hdHQECE5pZGF5BA0KTnVyb2F1aXJ1dHVhBA5PbWVnYSBQb3J1bmdhBAVPS1RXBAlxZWtrNWlUVwQJcWlsYWZ2Y2YEDQpSc2NyaXB0BAdSaHluYWkEC1Nhd2luY2xvbmcEBDAzOAQOU29ycnlJbVJseUJhZAQEMDg4BA0KVHNtU3VjY21hBAQwMjMECXRlZmlsbGluBAxUaGUgS2lsYUJveQQGSUFtU3dvcmRzcwQQV2VHZXR0aW5QYWlkQmJ5BAtXaW5pZnJlZHBHBAQwODUECVh0cmFTaDF0BAZZb25pZQQJWWVlZXR6dXMEDQpZdWJlZSBFeHBlcnQECXp2dHl2aXBkBA0KenZydWFnaWx6AQE="),nil,"bt",_ENV))()
-- 0.64